# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    restart: always
    image: mtgdb
    container_name: mtgdb
    build:
      context: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
